file = entry*

entry = complex | simple
complex = ( property_name class_name | class_name instance_name? ) ( "{" entry* "}" | "[" property_value* "]" )
simple = property_name property_value

class_name = IDENT
property_name = IDENT
instance_name = STRING
property_value = INT | FLOAT | STRING | BOOL
