file = definition*

definition = block | section | entry
block = name contents
section = name STRING contents
contents = "{" entry* "}" | "[" value* "]"
entry = name value | name block
value = ( INT | FLOAT | STRING | BOOL )
